### ISSUE TITLE
Heading Delta

### ISSUE THREAD

**Issue by AuderySun** [raphael-sch/map2seq_vln#1]
Is the condition in this line correct? Shouldn't it be `a<=-180`?
https://github.com/raphael-sch/map2seq_vln/blob/3f27260821fc8a0c194eeea95b581ab1f0d41224/vln/base_navigator.py#L30

**Comment by raphael-sch** [comment]
I think you are correct, but the code still works as intended because of the first if-clause. When I wrote it I was wondering why I can't remove this seemingly useless clause.
